package pojo;
// Generated Apr 15, 2018 11:33:52 AM by Hibernate Tools 3.6.0



/**
 * DiemdanhId generated by hbm2java
 */
public class DiemdanhId  implements java.io.Serializable {


     private int idmonhoc;
     private int idsinhvien;

    public DiemdanhId() {
    }

    public DiemdanhId(int idmonhoc, int idsinhvien) {
       this.idmonhoc = idmonhoc;
       this.idsinhvien = idsinhvien;
    }
   
    public int getIdmonhoc() {
        return this.idmonhoc;
    }
    
    public void setIdmonhoc(int idmonhoc) {
        this.idmonhoc = idmonhoc;
    }
    public int getIdsinhvien() {
        return this.idsinhvien;
    }
    
    public void setIdsinhvien(int idsinhvien) {
        this.idsinhvien = idsinhvien;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DiemdanhId) ) return false;
		 DiemdanhId castOther = ( DiemdanhId ) other; 
         
		 return (this.getIdmonhoc()==castOther.getIdmonhoc())
 && (this.getIdsinhvien()==castOther.getIdsinhvien());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdmonhoc();
         result = 37 * result + this.getIdsinhvien();
         return result;
   }   


}


