package pojo;
// Generated Apr 15, 2018 11:33:52 AM by Hibernate Tools 3.6.0



/**
 * Diemdanh generated by hbm2java
 */
public class Diemdanh  implements java.io.Serializable {


     private DiemdanhId id;
     private Integer t1;
     private Integer t2;
     private Integer t3;
     private Integer t4;
     private Integer t5;
     private Integer t6;
     private Integer t7;
     private Integer t8;
     private Integer t9;
     private Integer t10;
     private Integer t11;
     private Integer t12;
     private Integer t13;
     private Integer t14;
     private Integer t15;

    public Diemdanh() {
    }

	
    public Diemdanh(DiemdanhId id) {
        this.id = id;
    }
    public Diemdanh(DiemdanhId id, Integer t1, Integer t2, Integer t3, Integer t4, Integer t5, Integer t6, Integer t7, Integer t8, Integer t9, Integer t10, Integer t11, Integer t12, Integer t13, Integer t14, Integer t15) {
       this.id = id;
       this.t1 = t1;
       this.t2 = t2;
       this.t3 = t3;
       this.t4 = t4;
       this.t5 = t5;
       this.t6 = t6;
       this.t7 = t7;
       this.t8 = t8;
       this.t9 = t9;
       this.t10 = t10;
       this.t11 = t11;
       this.t12 = t12;
       this.t13 = t13;
       this.t14 = t14;
       this.t15 = t15;
    }
   
    public DiemdanhId getId() {
        return this.id;
    }
    
    public void setId(DiemdanhId id) {
        this.id = id;
    }
    public Integer getT1() {
        return this.t1;
    }
    
    public void setT1(Integer t1) {
        this.t1 = t1;
    }
    public Integer getT2() {
        return this.t2;
    }
    
    public void setT2(Integer t2) {
        this.t2 = t2;
    }
    public Integer getT3() {
        return this.t3;
    }
    
    public void setT3(Integer t3) {
        this.t3 = t3;
    }
    public Integer getT4() {
        return this.t4;
    }
    
    public void setT4(Integer t4) {
        this.t4 = t4;
    }
    public Integer getT5() {
        return this.t5;
    }
    
    public void setT5(Integer t5) {
        this.t5 = t5;
    }
    public Integer getT6() {
        return this.t6;
    }
    
    public void setT6(Integer t6) {
        this.t6 = t6;
    }
    public Integer getT7() {
        return this.t7;
    }
    
    public void setT7(Integer t7) {
        this.t7 = t7;
    }
    public Integer getT8() {
        return this.t8;
    }
    
    public void setT8(Integer t8) {
        this.t8 = t8;
    }
    public Integer getT9() {
        return this.t9;
    }
    
    public void setT9(Integer t9) {
        this.t9 = t9;
    }
    public Integer getT10() {
        return this.t10;
    }
    
    public void setT10(Integer t10) {
        this.t10 = t10;
    }
    public Integer getT11() {
        return this.t11;
    }
    
    public void setT11(Integer t11) {
        this.t11 = t11;
    }
    public Integer getT12() {
        return this.t12;
    }
    
    public void setT12(Integer t12) {
        this.t12 = t12;
    }
    public Integer getT13() {
        return this.t13;
    }
    
    public void setT13(Integer t13) {
        this.t13 = t13;
    }
    public Integer getT14() {
        return this.t14;
    }
    
    public void setT14(Integer t14) {
        this.t14 = t14;
    }
    public Integer getT15() {
        return this.t15;
    }
    
    public void setT15(Integer t15) {
        this.t15 = t15;
    }




}


