package pojo;
// Generated Apr 15, 2018 11:33:52 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Monhoc generated by hbm2java
 */
public class Monhoc  implements java.io.Serializable {


     private int idmonhoc;
     private String tenmonhoc;
     private Date ngaybd;
     private Date ngaykt;
     private Integer thu;
     private Date giobd;
     private Date giokt;
     private String phong;

    public Monhoc() {
    }

	
    public Monhoc(int idmonhoc) {
        this.idmonhoc = idmonhoc;
    }
    public Monhoc(int idmonhoc, String tenmonhoc, Date ngaybd, Date ngaykt, Integer thu, Date giobd, Date giokt, String phong) {
       this.idmonhoc = idmonhoc;
       this.tenmonhoc = tenmonhoc;
       this.ngaybd = ngaybd;
       this.ngaykt = ngaykt;
       this.thu = thu;
       this.giobd = giobd;
       this.giokt = giokt;
       this.phong = phong;
    }
   
    public int getIdmonhoc() {
        return this.idmonhoc;
    }
    
    public void setIdmonhoc(int idmonhoc) {
        this.idmonhoc = idmonhoc;
    }
    public String getTenmonhoc() {
        return this.tenmonhoc;
    }
    
    public void setTenmonhoc(String tenmonhoc) {
        this.tenmonhoc = tenmonhoc;
    }
    public Date getNgaybd() {
        return this.ngaybd;
    }
    
    public void setNgaybd(Date ngaybd) {
        this.ngaybd = ngaybd;
    }
    public Date getNgaykt() {
        return this.ngaykt;
    }
    
    public void setNgaykt(Date ngaykt) {
        this.ngaykt = ngaykt;
    }
    public Integer getThu() {
        return this.thu;
    }
    
    public void setThu(Integer thu) {
        this.thu = thu;
    }
    public Date getGiobd() {
        return this.giobd;
    }
    
    public void setGiobd(Date giobd) {
        this.giobd = giobd;
    }
    public Date getGiokt() {
        return this.giokt;
    }
    
    public void setGiokt(Date giokt) {
        this.giokt = giokt;
    }
    public String getPhong() {
        return this.phong;
    }
    
    public void setPhong(String phong) {
        this.phong = phong;
    }




}


