package pojo;
// Generated Apr 15, 2018 11:33:52 AM by Hibernate Tools 3.6.0



/**
 * Sinhvien generated by hbm2java
 */
public class Sinhvien  implements java.io.Serializable {


     private int idsinhvien;
     private String tensinhvien;

    public Sinhvien() {
    }

	
    public Sinhvien(int idsinhvien) {
        this.idsinhvien = idsinhvien;
    }
    public Sinhvien(int idsinhvien, String tensinhvien) {
       this.idsinhvien = idsinhvien;
       this.tensinhvien = tensinhvien;
    }
   
    public int getIdsinhvien() {
        return this.idsinhvien;
    }
    
    public void setIdsinhvien(int idsinhvien) {
        this.idsinhvien = idsinhvien;
    }
    public String getTensinhvien() {
        return this.tensinhvien;
    }
    
    public void setTensinhvien(String tensinhvien) {
        this.tensinhvien = tensinhvien;
    }




}


