
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import pojo.Diemdanh;
import pojo.DiemdanhId;
import pojo.Monhoc;
import pojo.Sinhvien;
import util.HibernateUtil;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author DELL
 */
public class pnDiemDanh extends javax.swing.JPanel {

    /**
     * Creates new form pnDiemDanh
     */
    login lg;
    public pnDiemDanh() {
        initComponents();
    }
    public pnDiemDanh(login l) {
        lg=l;
        initComponents();
        try {
            Session session = HibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();
            Query q = session.createQuery("select m.tenmonhoc from pojo.Monhoc m");
            List resultList = q.list();
            ArrayList<String> ls=new ArrayList<String>();
            for(Object o:resultList)
            {
                ls.add(o.toString());
            }
            jComboBox1.setModel(new DefaultComboBoxModel(ls.toArray()));                      
            session.getTransaction().commit();
        } catch (HibernateException he) {
            he.printStackTrace();
        }
        for(int i=1;i<=15;i++)
        {
            jTable1.setValueAt(i, i-1, 0);
        }
        jLabel2.setText("Mã Sinh Viên: "+lg.geti());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("Chọn môn");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Điểm danh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tuần", "Điểm danh"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(68, 68, 68)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        for(int i=1;i<=15;i++)
        {
            jTable1.setValueAt(false, i-1, 1);
        }
        try {
            Session session = HibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();
            Query q=session.createQuery("select dd from pojo.Diemdanh dd, pojo.Monhoc mh where dd.id.idmonhoc=mh.idmonhoc and mh.tenmonhoc=:tenmonhoc and dd.id.idsinhvien=:idsinhvien");
            q.setParameter("tenmonhoc", jComboBox1.getSelectedItem());
            q.setParameter("idsinhvien", lg.geti());
            List resultList = q.list();
            for(Object o:resultList)
            {
                Diemdanh dd=(Diemdanh) o;
                if(dd.getT1()==1)
                    jTable1.setValueAt(true, 0, 1);
                else
                    jTable1.setValueAt(false,0,1);
                if(dd.getT2()!=null){
                if(dd.getT2()==1)
                    jTable1.setValueAt(true, 1, 1);
                else
                    jTable1.setValueAt(false,1,1);
                }               
                    
                if(dd.getT3()==1)
                    jTable1.setValueAt(true, 2, 1);
                else
                    jTable1.setValueAt(false,2,1);
                if(dd.getT4()==1)
                    jTable1.setValueAt(true, 3, 1);
                else
                    jTable1.setValueAt(false,3,1);
                if(dd.getT5()==1)
                    jTable1.setValueAt(true, 4, 1);
                else
                    jTable1.setValueAt(false,4,1);
                if(dd.getT6()==1)
                    jTable1.setValueAt(true, 5, 1);
                else
                    jTable1.setValueAt(false,5,1);
                if(dd.getT7()==1)
                    jTable1.setValueAt(true, 6, 1);
                else
                    jTable1.setValueAt(false,6,1);
                if(dd.getT8()==1)
                    jTable1.setValueAt(true, 7, 1);
                else
                    jTable1.setValueAt(false,7,1);
                if(dd.getT9()==1)
                    jTable1.setValueAt(true, 8, 1);
                else
                    jTable1.setValueAt(false,8,1);
                if(dd.getT10()==1)
                    jTable1.setValueAt(true, 9, 1);
                else
                    jTable1.setValueAt(false,9,1);
                if(dd.getT11()==1)
                    jTable1.setValueAt(true, 10, 1);
                else
                    jTable1.setValueAt(false,10,1);
                if(dd.getT12()==1)
                    jTable1.setValueAt(true, 11, 1);
                else
                    jTable1.setValueAt(false,11,1);
                if(dd.getT13()==1)
                    jTable1.setValueAt(true, 12, 1);
                else
                    jTable1.setValueAt(false,12,1);
                if(dd.getT14()==1)
                    jTable1.setValueAt(true, 13, 1);
                else
                    jTable1.setValueAt(false,13,1);
                if(dd.getT15()==1)
                    jTable1.setValueAt(true, 14, 1);
                else
                    jTable1.setValueAt(false,14,1);
            }
            
            
            
            session.getTransaction().commit();
        } catch (HibernateException he) {
            he.printStackTrace();
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Diemdanh dd=new Diemdanh();
        DiemdanhId id=new DiemdanhId();
        int idd=0;
        try {
            Session session = HibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();
            Query q = session.createQuery("from pojo.Monhoc");
            List resultList=q.list();
            for(Object o:resultList)
            {
                Monhoc temp=(Monhoc) o;
                if(temp.getTenmonhoc().equals(jComboBox1.getSelectedItem()))
                    idd=temp.getIdmonhoc();
            }
     
                id.setIdmonhoc(idd);
               // System.out.println(jTable1.getValueAt(i, 0));
                id.setIdsinhvien(lg.geti());
                dd.setId(id);
                if(jTable1.getValueAt(0, 1)!=null){
                    if((boolean)jTable1.getValueAt(0, 1)==true)
                        dd.setT1(1);
                    else
                        dd.setT1(0);
                }
                else
                    dd.setT1(0);
                if(jTable1.getValueAt(1, 1)!=null){
                    if((boolean)jTable1.getValueAt(1, 1)==true)
                        dd.setT2(1);
                    else
                        dd.setT2(0);
                }
                else
                    dd.setT2(0);
                if(jTable1.getValueAt(2, 1)!=null){
                    if((boolean)jTable1.getValueAt(2, 1)==true)
                        dd.setT3(1);
                    else
                        dd.setT3(0);
                }
                else
                    dd.setT3(0);
                if(jTable1.getValueAt(3, 1)!=null){
                    if((boolean)jTable1.getValueAt(3, 1)==true)
                        dd.setT4(1);
                    else
                        dd.setT4(0);
                }
                else
                    dd.setT4(0);
                if(jTable1.getValueAt(4, 1)!=null){
                    if((boolean)jTable1.getValueAt(4, 1)==true)
                        dd.setT5(1);
                    else
                        dd.setT5(0);
                }
                else
                    dd.setT5(0);
                if(jTable1.getValueAt(5, 1)!=null){
                    if((boolean)jTable1.getValueAt(5, 1)==true)
                        dd.setT6(1);
                    else
                        dd.setT6(0);
                }
                else
                    dd.setT6(0);
                if(jTable1.getValueAt(6, 1)!=null){
                    if((boolean)jTable1.getValueAt(6, 1)==true)
                        dd.setT7(1);
                    else
                        dd.setT7(0);
                }
                else
                    dd.setT7(0);
                if(jTable1.getValueAt(7, 1)!=null){
                    if((boolean)jTable1.getValueAt(7, 1)==true)
                        dd.setT8(1);
                    else
                        dd.setT8(0);
                }
                else
                    dd.setT8(0);
                if(jTable1.getValueAt(8, 1)!=null){
                    if((boolean)jTable1.getValueAt(8, 1)==true)
                        dd.setT9(1);
                    else
                        dd.setT9(0);
                }
                else
                    dd.setT9(0);
                if(jTable1.getValueAt(9, 1)!=null){
                    if((boolean)jTable1.getValueAt(9, 1)==true)
                        dd.setT10(1);
                    else
                        dd.setT10(0);
                }
                else
                    dd.setT10(0);
                if(jTable1.getValueAt(10, 1)!=null){
                    if((boolean)jTable1.getValueAt(10, 1)==true)
                        dd.setT11(1);
                    else
                        dd.setT11(0);
                }
                else
                    dd.setT11(0);
                if(jTable1.getValueAt(11, 1)!=null){
                   if((boolean)jTable1.getValueAt(11, 1)==true)
                        dd.setT12(1);
                    else
                        dd.setT12(0);
                }
                else
                    dd.setT12(0);
                if(jTable1.getValueAt(12, 1)!=null){
                    if((boolean)jTable1.getValueAt(12, 1)==true)
                        dd.setT13(1);
                    else
                        dd.setT13(0);
                }
                else
                    dd.setT13(0);
                if(jTable1.getValueAt(13, 1)!=null){
                    if((boolean)jTable1.getValueAt(13, 1)==true)
                        dd.setT14(1);
                    else
                        dd.setT14(0);
                }
                else
                    dd.setT14(0);
                if(jTable1.getValueAt(14, 1)!=null){
                    if((boolean)jTable1.getValueAt(14, 1)==true)
                        dd.setT15(1);
                    else
                        dd.setT15(0);
                }
                else
                    dd.setT15(0);
                
              q=session.createQuery("update pojo.Diemdanh dd set dd.t1=:t1,dd.t2=:t2,dd.t3=:t3,t4=:t4,"
                      + "t5=:t5,t6=:t6,t7=:t7,t8=:t8,t9=:t9,t10=:t10,t11=:t11,t12=:t12,t13=:t13,t14=:t14,t15=:t15 "
                        + "where dd.id.idsinhvien=:idsinhvien and dd.id.idmonhoc=:idmonhoc");
              q.setParameter("t1", dd.getT1());
              q.setParameter("t2", dd.getT2());
              q.setParameter("t3", dd.getT3());
              q.setParameter("t4", dd.getT4());
              q.setParameter("t5", dd.getT5());
              q.setParameter("t6", dd.getT6());
              q.setParameter("t7", dd.getT7());
              q.setParameter("t8", dd.getT8());
              q.setParameter("t9", dd.getT9());
              q.setParameter("t10", dd.getT10());
              q.setParameter("t11", dd.getT11());
              q.setParameter("t12", dd.getT12());
              q.setParameter("t13", dd.getT13());
              q.setParameter("t14", dd.getT14());
              q.setParameter("t15", dd.getT15());
              q.setParameter("idsinhvien", dd.getId().getIdsinhvien());
              q.setParameter("idmonhoc", idd);
              q.executeUpdate();
          
            session.getTransaction().commit();
        } catch (HibernateException he) {
            he.printStackTrace();
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
